Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |vb|
  	vb.gui = false
  	vb.memory = "4096"
  	vb.cpus = 2
  	vb.name = "WebGoat-workshop"
	vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
  config.vm.provider "vmware_fusion" do |vf|
    vf.gui = false
    vf.vmx["memsize"] = 4096
    vf.vmx["numvcpus"] = 2
    vf.vmx["displayname"] = "WebGoat-Workshop"
  end

  config.vm.provision :shell, inline: <<-SHELL
    type docker > /dev/null 2>&1 || { wget -qO- https://get.docker.com/ | sh; }
    docker run --name="webgoat" --restart="always" -p 8080:8080 -i webgoat/webgoat-8.0 /home/webgoat/start.sh             
    SHELL

end
